### ISSUE TITLE
Google not working

### ISSUE THREAD

**Issue by Homercat1234** [Discord-Bot-Maker-Mods/DBM-Mods#113]
Bot is ready!
DBM MODS (Node Module Installer v2.1) Attempting To Install Node Module: 'google-it'. Please wait...
DBM MODS (Node Module Installer v2.1): Node Module 'google-it' does not exist!
Command failed: npm install google-it --loglevel=error --save
DBM MODS (Node Module Installer v2.1) Attempting To Install Node Module: 'google-it'. Please wait...
DBM MODS (Node Module Installer v2.1): Node Module 'google-it' does not exist!
Command failed: npm install google-it --loglevel=error --save
Error with Event "Google Search", Action #2: Error: Cannot find module 'google-it'

Can some one help? Problem is still there on beta

**Comment by Almeeida** [comment]
The module which Google Search used is now broken.
Also that error you are getting has nothing to do with the mod.
You just need to run the bot using cmd
![](https://i.imgur.com/IoOW9xG.png)
![](https://cdn.discordapp.com/attachments/374961417016573962/432632135040368650/how_to_open_cmd.gif)
It's also better if you ask for support in the servers instead of here, [click here](https://discord.gg/DMDvzSe)

**Comment by LasseNiermann** [comment]
//Closed due to inactivity. You may use the [DBM Network server](https://steamcommunity.com/app/682130/discussions/0/1500126447401899314/) for support.
