### ISSUE TITLE
Edit Voice Channel Console Error

### ISSUE THREAD

**Issue by MZPL** [Discord-Bot-Maker-Mods/DBM-Mods#145]
In Console:
Error with Event "Edit Channel", Action #3: TypeError: this.getVoiceChannel is not a function

**Comment by LasseNiermann** [comment]
Hey. 
Thank you for opening an issue. We need some more information. 
Are you using the DBM Beta and/or beta mods?

Kind regards,
Lasse

**Comment by MZPL** [comment]
I'm using DBM Beta Mods, without DBM Beta.

**Comment by LasseNiermann** [comment]
Okay. That's the problem. In order to use all features of the DBM Mods (Beta), you need to use the DBM Beta as well. Most music and voice functions are part of the DBM Beta. You are most likely trying to edit a voice channel.

Here is how to install the beta:
0. Make a backup of your project's data folder!
1. Close DBM
2. Open Steam
3. Open your software library
4. Right-click Discord Bot Maker
5. Select Properties (at the bottom)
6. Select Betas
7. Select beta in the drop down menu (no key is required)
8. DBM should update now. Otherwise restart Steam.

Have a nice day!

**Comment by MZPL** [comment]
Thank You! :)
You can close this "issue".
