### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by SoulOfSalutations** [Discord-Bot-Maker-Mods/DBM-Mods#264]
I got the mod and installed it like it said to do. everything booted up normally exept when i tried running the bot even without USING any of the mods in the code it just says "There was an error".
![Capture677](https://user-images.githubusercontent.com/58421066/72406325-d8e08100-3729-11ea-9fdf-d3b21f6626bc.PNG)

**Comment by Almeeida** [comment]
That's because when you're using Modifications you must run your bot using the Command Prompt.

Here's how:

This process requires [NodeJS](https://nodejs.org/en/download/) to be installed on your computer.

To run the bot in the Command Prompt, follow these steps:
- Inside DBM: Press Project -> Open Project Directory
- Inside the Project Directory: Click the address bar at the top and delete everything in it
- Type `cmd` and press enter
- Inside the Command Prompt: Type: `node bot.js`

Example: ![example](https://media.discordapp.net/attachments/374961417016573962/432632135040368650/how_to_open_cmd.gif)
