### ISSUE TITLE
Set Voice Channel Perms Bug

### ISSUE THREAD

**Issue by Marsmallowman** [Discord-Bot-Maker-Mods/DBM-Mods#82]
Hello to great developers of DBM and DBM Mods, i like to ask you, is this bug? (image attached) Or i copied something wrong?(Its from DBM-Mods-master.zip package) Thx in advance, Marsmallowman (Translated by genial google translate :/ )
![image](https://user-images.githubusercontent.com/44581751/47664661-cff4a580-db9f-11e8-9bdc-33c3889c4622.png)

**Comment by LasseNiermann** [comment]
Hey @Marsmallowman !
Thanks for asking. This is not a bug, you need to install the DBM Beta in order to use DBM Mods.
Here is the installation process:
1. Close DBM
2. Open Steam
3. Open your software library
4. Right click Discord Bot Maker
5. Select Properties (at the bottom)
6. Select Betas
7. Select beta in the drop down menu (no key is required)
8. DBM should update now. Otherwise restart Steam.

Have fun!
~ Lasse

**Comment by Marsmallowman** [comment]
Thx for help @LasseNiermann, working perfectly!!!!
